### ISSUE TITLE
import lib.hpcore as hpcore

### ISSUE THREAD

**Issue by tanyalama** [gwct/hyphy-interface#8]
Hi! Attempting to use hyphy_to_csv.py to parse the results for a huge set of .json output files from hyphy absrel. Unfortunately one of the requisites is lib.hpcore called as 

import sys, os, argparse, lib.hpcore as hpcore
line 6 in hyphy_to_csv.py 

I am not sure what package you meant to call here but can't locate lib.hpcore on conda repository or anywhere else to install it. I attempted to run hpcore.py hoping it would generate the library somewhere, but no luck. Where can I access lib.hpcore to run these functions please? Thank you

**Comment by gwct** [comment]
Hey there,
That is just a library within the package, not an external package you would find anywhere else. I've updated how it looks for those libraries now so pull the latest code and try again. Let me know if it works!
-Gregg

**Comment by tanyalama** [comment]
Hey Gregg, 
Thank you SO much! It is working. Unfortunately it only loops through about 4000 of my 17k genes before I get a decoder error: 
json.decoder.JSONDecodeError: Expecting value: line 15 column 28 (char 972)

Don't want to take up your time! I assume this means I have a corrupt json file somewhere. Your fix_json.sh script didn't seem to alleviate this issue. Looking for other methods of checking json files before I send them through the parser if anything comes to mind.

**Comment by gwct** [comment]
Glad we fixed that error!
For the new one, it definitely sounds like one of the .json files is incomplete, like you said. If your hyphy run had any errors or warnings print out that could give a clue as to which file it is.
Otherwise, you could find the file that corresponds to the model you ran in the `lib/` folder and just add a print statement to the loop that reads the .json files in the `parse()` function. For example, if you ran BUSTED, you could open `lib/busted.py` add `print(f)` just after [line 115](https://github.com/gwct/hyphy-interface/blob/f3d712227a8d58dbc18359328fb89a429624163b/lib/busted.py#L115), and then you could see which one it crashes on.

**Comment by tanyalama** [comment]
Hi Gregg! 
Ok update -- that specific fix did not help (print (f) at line 253 in /lib/absrel.py) for my run of hyphy_to_csv. However uncommenting (removing #) from print (f) at lines 270 and 387 in absrel.py (right after Track Progress) was a huge help. Now it prints out jsons until it hits one that is problematic. The commonality among all of the problematic json files is not that they are empty (in my case), just that they have -nan for the following fields: 
"Corrected P-value":-nan,
"LRT":-nan,
"Uncorrected P-value":-nan,

So in theory, I could just loop through my files and look for -nan fields and that would give me an idea of which files need to be inspected before parsing. Maybe next time.

If anyone else struggles with this, I've written a little hackMD here for checking json files before parsing. Thank you Gregg for being so helpful!
[tanya_edits_absrel.txt](https://github.com/gwct/hyphy-interface/files/9893909/tanya_edits_absrel.txt)
[processing-hyphy-absrel-selection-results.pdf](https://github.com/gwct/hyphy-interface/files/9894054/processing-hyphy-absrel-selection-results.pdf)

**Comment by gwct** [comment]
Awesome! Thanks for the updated script and methods summary.
It looks like Hyphy changed how they represent nans, or this is a case we just haven't encountered before. Regardless, we should be able to update `fix_json.sh` to catch this as well. I'll do a bit of testing on it and post again here when it is up.

**Comment by gwct** [comment]
Ok, I've added `-nan` to the things that `fix_json.sh` checks for so that should be able to fix those files now, though that doesn't get at the underlying reason why Hyphy produced a NaN, it just allows this post-processing script to run.

I also added `check_json.sh`, which if you give it a directory of .json files it should print the files that have the problematic entries in it that you could then run through `fix_json.sh`. It's all pretty rudimentary, but hopefully I can make it nicer later.
